# Install and load the strucchange package
install.packages("strucchange", repos = "https://cran.mirror.garr.it/CRAN/")
install.packages("SupMZ", repos = "https://cran.mirror.garr.it/CRAN/")
install.packages("tseries", repos = "https://cran.mirror.garr.it/CRAN/")
install.packages("skewt", repos = "https://cran.mirror.garr.it/CRAN/")
install.packages("fitdistrplus", repos = "https://cran.mirror.garr.it/CRAN/")
install.packages("glogis", repos = "https://cran.mirror.garr.it/CRAN/")
install.packages("sn", repos = "https://cran.mirror.garr.it/CRAN/")

library(strucchange)
library(SupMZ)
library(tseries)
library(skewt)
library(fitdistrplus)
library(glogis)
library(sn)