
install.packages("strucchange", repos = "https://cran.stat.unipd.it/")
install.packages("SupMZ", repos = "https://cran.stat.unipd.it/")
install.packages("tseries", repos = "https://cran.stat.unipd.it/")
install.packages("skewt", repos = "https://cran.stat.unipd.it/")
install.packages("fitdistrplus", repos = "https://cran.stat.unipd.it/")
install.packages("glogis", repos = "https://cran.stat.unipd.it/")
install.packages("sn", repos = "https://cran.stat.unipd.it/")

library(strucchange)
library(SupMZ)
library(tseries)
library(skewt)
library(fitdistrplus)
library(glogis)
library(sn)